a=int(input("Enter first number:: "))
b=int(input("Enter second numbers:: "))
print("Addition of two numbers:: ",a+b)
print("Substraction of two numbers:: ",a-b)
print("Multification of two numbers:: ",a*b)
print("Division of two numbers:: ",a/b)
print("Floor Divition of two numbers:: ",a//b)
print("Modulas of two numbers:: ",a%b)
print("Power of two numbers:: ",a**b)